language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- pip install -r requirements_test.txt
- flake8 .
deploy:
  provider: heroku
  api_key:
    secure: Bq/gOt5ViGr/s0k9MWmbmF1wvAUhULfFGT8FbbAW/VsosX+DPlKUDOBkZqcBBrYwozskNHeH6+tuP3Fo4JpHO0oLr/h0+OX4I+TMKFx+DbljVTNCVYhOYlj4CWrZTcXgHqmH8f0xSOWaFI/cnrzHyR5tzBg4CELWmROfdn+XP/lfnLb2qirYx7CgsQjs/nX5lxbTkaCQDrpFoZ+AwyEJ9gvz4/FmQEzNC0E7lNJzBFBXHfGqzfBNOrSpy3e/tvieqVuaCMHScJ/5zZeGnnXkhlTuFL5o/tnoPiee6lztb5hkdBY2H9WKgOsKsPo/HnsEDZN1+bfKUx9r3cHIB2jDq35Uc5qWajUf01iM6rLiNmGhOdOe0O8MYJX2S0vBEPyfs2HI5YneFtrMONSCrZuQaX6zOr0vszOUrReQZnBtv9M/LoPTvVUWFr4B4ez1FrSzSCFBTFbIu90ISGRGqBb6Th86uw+CRoluaeMVD6lPOuxE9OcswmY0vxyzhxdtBsOYPjiC8BXaw/VkTsru0Us01S4sS09rgBol5SZjoFSyANXqPxpVlfEJHtgORta46wEtwi1mtmBVyVMZzHcnasqqf8SRQqB0PTl68E7XYU64EikbnxASO/d6RN0idIEo5q43+970KXPMN81PtZsZ6PezCCwSACs4Ug0ZRtX2VB18aOM=
  app:
    master: mash-place
  on:
    repo: MashSoftware/place-ui
sudo: false
